scrape_configs:
  - job_name: 'puli-main'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - 'prometheus:9090'
        - '70.34.209.48:443'
        - '70.34.209.48:80'
        - 'puli-main:80'
        - 'puli-main:443'

rule_files:
  - 'rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093