scrape_configs:
  - job_name: 'puli-main'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets:
          ['puli-main:443']
    tls_config:
      insecure_skip_verify: true

rule_files:
  - 'rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093