CREATE TABLE IF NOT EXISTS PuliDb.Album(
ID INT AUTO_INCREMENT NOT NULL,
CREATED_AT DATETIME(6) NOT NULL,
MODIFIED_AT DATETIME(6) NOT NULL,
TITLE VARCHAR(50) NOT NULL,
DESCRIPTION TEXT,
PRIMARY KEY (ID))
;