CREATE TABLE IF NOT EXISTS PuliDb.Text(
ID INT AUTO_INCREMENT not null,
TEXT_GROUP VARCHAR(50) not null,
TEXT_KEY VARCHAR(50) not null,
TEXT TEXT not null,
PRIMARY KEY (ID))
;
INSERT INTO PuliDb.Text (TEXT_GROUP, TEXT_KEY, TEXT) VALUES ('contact', 'name', 'Carina Karlsson');
INSERT INTO PuliDb.Text (TEXT_GROUP, TEXT_KEY, TEXT) VALUES ('contact', 'number', '+46(0)708 48 75 02');
INSERT INTO PuliDb.Text (TEXT_GROUP, TEXT_KEY, TEXT) VALUES ('contact', 'address', 'Slågarpsvägen 264-0 <br>Trelleborg - Sverige');
INSERT INTO PuliDb.Text (TEXT_GROUP, TEXT_KEY, TEXT) VALUES ('aboutPuli', 'mainText', 'Det var en gång en puli...');
INSERT INTO PuliDb.Text (TEXT_GROUP, TEXT_KEY, TEXT) VALUES ('about', 'mainText', 'Vår kennel har uppfödning av den ungerska rasen Puli. Vår kennel vill ha sunda och friska hundar med bra temperament.<br>De ska vara rastypiska och bör ha kvar sitt arv som vakt och vallhund.<br>Vi strävar efter att alla hundar som är i avel är HD-röntgade med godkänt resultat och ska vara ögonlysta.<br>Kollar även avelshundar för DM.<br><br>En Puli är väldigt lättlärd och älskar att få göra något, men ändå ingen hund som &quot;klättrar på väggarna&quot;.<br>De anpassar sig bra och är lätta att ha med sig.<br>Jag (Carina) sysslar gärna lite med vallning, agility (som de bara älskar) och lydnad.<br>Det är bra både för en själv och hunden att få syssla med lite olika saker, både hemma och i annan miljö.<br><br>Vi är en kennel som har uppfödning i liten skala, de nyfödda valparna föds i valpsängen som står i sovrummet, allt för att ha lite kontroll på läget.<br><br>Tikarna har klarat av det mesta själv utan någon större hjälp.<br><br>Mamman kan gå ut och in som hon vill, hon får dia så länge hon vill, ibland ända till valpen är leveransklar.<br>Vid fyra veckors ålder börjar de få riktig mat. Nu börjar de bli riktigt busiga, men där finns en rejäl hage plus att de även får komma ut och härja ibland, både ute och inne. Valparna blir uppfostrade av både tik och hane.<br><br>Att valparna får träffa barn redan från början är mycket positivt för den fortsatta kontakten framöver.<br>Vi vänjer dem vid kloklippning, rycka öronhåren o annan viktig fysisk kontakt.<br><br>Om möjligt så vid halvåret träffas valpköpare med sina hundar, sen även vid året, mycket omtyckta träffar som de flesta gärna vill ha uppföljning på.<br>Vi pratar hund och allt som hör där till, pälsvård, mat uppfostran mm.<br>Alla är välkomna att ringa vid frågor och problem, ring hellre en gång för mycket.<br><br>Vi brukar ibland ha kennelträff, där allt från unghundr till gamlingar sluter upp..<br>');