CREATE TABLE IF NOT EXISTS PULI_DB.TEST (
  ID INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  ADD_TS DATETIME(6) NOT NULL,
  PRIMARY KEY (ID))
ENGINE = InnoDB;